//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Instituto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumno()
        {
            this.curso = new HashSet<curso>();
        }
    
        public int Legajo { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        [Display (Name = "Fecha de nacimiento")]
        public Nullable<System.DateTime> FecNac { get; set; }
        public Nullable<int> DNI { get; set; }
        public string Mail { get; set; }
        [Display(Name = "Teléfono")]
        public Nullable<int> Tel { get; set; }
        [Display(Name = "Antigüedad")]
        public Nullable<int> Antig { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<curso> curso { get; set; }
    }
}
