//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Instituto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursos
    {
        public int IdCurso { get; set; }
        public int Legajo_Alumn { get; set; }
        public string nombre_Alumn { get; set; }
        public string Apellido_Alumn { get; set; }
    }
}
