//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Instituto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Cursos
    {
        public int IdCurso { get; set; }
        [DisplayName("Número de Legajo")]
        public int Legajo_Alumn { get; set; }
        [DisplayName("Nombre de Alumno")]
        public string nombre_Alumn { get; set; }
        [DisplayName("Apellido")]
        public string Apellido_Alumn { get; set; }
    }
}
